[package]
name = "git-treemanager"
description = "A tool to manage git trees"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
git2 = "0.18"
anyhow = "1.0"
